name: Create Release and ZIP
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'LICENSE*'
      - 'README*'
      - '.gitignore'
      - '.github/**'
  pull_request:
    branches:
      - main
    types: [closed]
    paths-ignore:
      - 'LICENSE*'
      - 'README*'
      - '.gitignore'
      - '.github/**'
jobs:
  build:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Get version from PHP file
        id: get_version
        run: |
          VERSION=$(grep -m 1 "Version:" teva-preguntas.php | awk '{print $3}')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Create ZIP file
        run: |
          zip -r teva-preguntas.zip . -x "*.git*" "*.github*" "README*" "LICENSE*"
      - name: Create or Update Release
        uses: softprops/action-gh-release@v2
        with:
          files: teva-preguntas.zip
          name: Release v${{ steps.get_version.outputs.version }}
          tag_name: v${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}